#!/usr/bin/env php
<?php

// Determine location of autoload.php and include it
if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

use Crafter\Installer\Commands\NewCommand;
use Crafter\Installer\Commands\Show\ShowFrameworksCommand;
use Symfony\Component\Console\Application;

$app = new Application('Crafter installer', '0.1.0');
$app->add(new NewCommand);
$app->add(new ShowFrameworksCommand);
$app->run();
